Avoid crash in compactOOOHead if wbl is nil
grafana/mimir-prometheus pull request #452
Opened 2023-03-10 19:08 UTC by bboreham

Trying to avoid this:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10dc1bd]

goroutine 82338 [running]:
github.com/prometheus/prometheus/tsdb/wlog.(*WL).NextSegmentSync(0x0)
        /backend-enterprise/vendor/github.com/prometheus/prometheus/tsdb/wlog/wlog.go:478 +0x3d
github.com/prometheus/prometheus/tsdb.NewOOOCompactionHead(0xc014a1d400)
        /backend-enterprise/vendor/github.com/prometheus/prometheus/tsdb/ooo_head_read.go:285 +0x3a
github.com/prometheus/prometheus/tsdb.(*DB).compactOOOHead(0xc001125d10)
        /backend-enterprise/vendor/github.com/prometheus/prometheus/tsdb/db.go:1165 +0x4f
github.com/prometheus/prometheus/tsdb.(*DB).CompactOOOHead(0xc001125d10?)
        /backend-enterprise/vendor/github.com/prometheus/prometheus/tsdb/db.go:1158 +0x96
github.com/grafana/mimir/pkg/ingester.(*userTSDB).compactHead(0xc00f371440, 0x6ddd00)
        /backend-enterprise/vendor/github.com/grafana/mimir/pkg/ingester/user_tsdb.go:201 +0x378
github.com/grafana/mimir/pkg/ingester.(*Ingester).compactBlocks.func1({0xc0064bc120?, 0xc008fdef28?}, {0xc001ce10d3, 0x6})
        /backend-enterprise/vendor/github.com/grafana/mimir/pkg/ingester/ingester.go:2111 +0x3c5
github.com/grafana/dskit/concurrency.ForEachUser.func1()
        /backend-enterprise/vendor/github.com/grafana/dskit/concurrency/runner.go:45 +0x14d
created by github.com/grafana/dskit/concurrency.ForEachUser
        /backend-enterprise/vendor/github.com/grafana/dskit/concurrency/runner.go:36 +0x125
```

2023-03-10 19:10 UTC, 56quarters approved these changes

2023-03-10 19:23 UTC, npazosmendez approved these changes

2023-03-11 11:19 UTC, jesusvazquez commented
This PR is ready to be merged https://github.com/prometheus/prometheus/pull/11962 and I think it may solve the issue as well.

2023-03-13 05:02 UTC, codesome requested changes
This can create some unknown problems. I say unknown because we don't know why this `wbl` object was `nil` while ooo compaction is being called, so not compacting at all will lead to ooo data hanging around in the Head forever. I will review and merge @jesusvazquez's upstream fix today and vendor into mimir-prometheus.

2023-03-13 07:11 UTC, codesome commented
Fix was merged upstream. PR to get it into mimir-prometheus https://github.com/grafana/mimir-prometheus/pull/453

2023-03-13 07:11 UTC, closed without merging