Add EstimatedChunkCount() method to ChunkSeries
grafana/mimir-prometheus pull request #513
Opened 2023-07-05 05:45 UTC by charleskorn

See https://github.com/grafana/mimir/pull/5369.

2023-07-05 07:35 UTC, aknuds1 approved these changes
I lack familiarity, but LGTM FWIW.

2023-07-05 08:13 UTC, krajorama commented on storage/interface.go
> +	// EstimatedChunkCount returns an estimate of the number of chunks available from this ChunkSeries.
I think this should specify the requirement - if applicable - whether the estimate should be greater or equal or less or equal of the actual count. Is there such implicit requirement or can the estimate return anything?

2023-07-05 09:29 UTC, krajorama requested changes
Do I see correctly that we're going to iterate all samples? seriesToChunkEncoder.EstimatedChunkCount suggests so. 
That would mean that we touch the chunk, so we might as well just fetch the chunk count instead of estimating it. Also even better we could count up the size of chunks which can be all over the place due to OOO and native histograms.

I think this PR could be used for normal float series situations, but I think we should revisit it to look at actual chunk sizes and not estimate based on sample count.

2023-07-05 09:29 UTC, krajorama commented on storage/merge.go
> +			h.Push(iter)
Is this supposed to behave as a heap? Cause if I understand correctly you'd need to use the standard heap functions: https://pkg.go.dev/container/heap#Init 
Right now I think it doesn't order the elements in it - I'd just change to a slice if heap is not actually needed.

2023-07-05 09:29 UTC, krajorama commented on storage/merge.go
> +				chunkCountForThisTimePeriod += sampleCount / seriesToChunkEncoderSplit
Note: there was talk about introducing size limit instead of sample count limit for histogram chunks - not implemented yet. That would mean underestimating the chunk count, which is fine.

2023-07-05 17:52 UTC, codesome commented on storage/merge.go
> +			h.Push(iter)
If chunks are sorted by their mint, then we don't need the heap

2023-07-05 17:52 UTC, codesome commented on storage/series.go
> +func (s *seriesToChunkEncoder) EstimatedChunkCount() int {
Assuming this is called everytime for limits, this will effectively make us iterate on all the samples twice. I don't have a good way to make that more efficient at the moment (other than maybe `Series` interface getting maybe a `NumSamples()`), so noting this for the future in case we see any regression.

2023-07-05 17:52 UTC, codesome commented on storage/series.go
> +		if samplesInChunk == seriesToChunkEncoderSplit {
There is an off-by-1 case if we end up having `seriesToChunkEncoderSplit` number of samples in the last chunk.

2023-07-06 03:45 UTC, charleskorn commented on storage/interface.go
> +	// EstimatedChunkCount returns an estimate of the number of chunks available from this ChunkSeries.
It's really hard to set either requirement, so I've deliberately left it open. Happy to add that as a comment if you think it's necessary.

2023-07-06 03:58 UTC, charleskorn commented on storage/merge.go
> +			h.Push(iter)
>Is this supposed to behave as a heap? Cause if I understand correctly you'd need to use the standard heap functions: https://pkg.go.dev/container/heap#Init

Good catch - this should be using `heap.Push`, not `h.Push`. (`Push`ing each element is the same as creating the slice and then calling `Init`, and `compactChunkIterator.Next()` does the same thing, so I'd like to keep them consistent, even though it's more expensive.)

> If chunks are sorted by their mint, then we don't need the heap

`compactChunkIterator.Next()` (which this estimation function tries to emulate) doesn't assume the series are sorted, so we can't either.

2023-07-06 04:27 UTC, charleskorn commented on storage/merge.go
> +//   - it does not check if overlapping chunks have samples that swap back and forth between
Good point, I've added a comment in https://github.com/grafana/mimir-prometheus/commit/f71a97b460a691074fbf6766798b3377b8fa21f6

2023-07-06 04:28 UTC, charleskorn commented on storage/merge.go
> +				chunkCountForThisTimePeriod += sampleCount / seriesToChunkEncoderSplit
That's fine, we can also improve the estimation once that's in place.

2023-07-06 04:46 UTC, charleskorn commented on storage/series.go
> +func (s *seriesToChunkEncoder) EstimatedChunkCount() int {
An alternative to both of these more involved estimates (`seriesToChunkEncoder` and `NewCompactingChunkSeriesMerger`) is to just materialise the chunks and count them. 

Given neither of these more involved estimates seem to actually be used on the ingester query path in Mimir (both based on setting breakpoints on a local instance and also examining profiles from real prod cells), I'm tempted to try that as a simpler first approach and then we can try to more cheaply estimate the number of chunks if this turns out to be problematic.

2023-07-06 05:56 UTC, charleskorn commented
Based on tracing through the code a bit more, as well as verifying with a debugger, I don't believe `EstimatedChunkCount()` will ever be called on anything apart from `chunkSeriesEntry`. 

So to simplify this PR, I've replaced the complex estimations with simple but expensive iteration of the final chunks themselves for `seriesToChunkEncoder` and `NewCompactingChunkSeriesMerger`. These should never actually be used, but if my understanding turns out to be incorrect, then these will at least still work and we can optimise if need be.

2023-07-06 06:32 UTC, krajorama approved these changes
LGTM. Note: in case of native histograms, we'd need https://github.com/prometheus/prometheus/pull/12054 implemented to get best memory overload protection out of it, because currently histogram chunks can be 1K-64K.

2023-07-06 23:42 UTC, charleskorn commented
Given the approval from @krajorama, I'm going to merge this, but if anyone has any late feedback, let me know.

2023-07-06 23:42 UTC, merged